
- name: Ejecutar pruebas del Trabajo Práctico
  hosts: all
  become: true  # Permite ejecutar como sudo (necesario para el rol si cambia owners)

  vars_files:
    - vars/main.yml  # Si usás variables globales desde este archivo

  vars:
    Nombre_Grupo: "Grupo_7"  # Variable fija para el template de TP_INI

  roles:
    - TP_INI

  tasks:
    - name: "otra prueba"
      debug:
        msg: "Despues de la ejecucion del rol"  