
- name: Ejecutar pruebas del Trabajo Práctico
  hosts: all
  become: true 

  vars_files:
    - vars/main.yml  

  vars:
    Nombre_Grupo: "Ristagno_bartolomei"  

  roles:
    - TP_INI
    - Alta_Usuarios_ristagno_bartolomei
    - Sudoers_Ristagno_bartolomei
    - Instala-tools_Ristagno_bartolomei

