
- name: Ejecutar pruebas del Trabajo Práctico
  hosts: all
  become: true 

  vars_files:
    - vars/main.yml  

  vars:
    Nombre_Grupo: "Ristagno_bartolomei"  

  roles:
    - TP_INI

  tasks:
    - name: "otra prueba"
      debug:
        msg: "Despues de la ejecucion del rol"  